[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.22"
[package]
org = "hp"
name = "Auth"
version = "0.1.0"
distribution = "2201.12.7"

#[build-options]
#observabilityIncluded = true
#path = "libs/mysql-connector-java-8.0.11.jar"